### ISSUE TITLE
TextToSpeech not works in my android phone but its work in emulator

### ISSUE THREAD

**Issue by enock-meston** [gressus/softenido#49]
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.speech.tts.engine.CHECK_TTS_DATA }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1638)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
        at android.app.Activity.startActivityForResult(Activity.java:3457)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:3418)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at com.example.texttospeechexample.MainActivity.performSpeech(MainActivity.java:31)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:397) 
        at android.view.View.performClick(View.java:4463) 
        at android.view.View$PerformClick.run(View.java:18789) 
        at android.os.Handler.handleCallback(Handler.java:808) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5299) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by enock-meston** [comment]
package com.example.texttospeechexample;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.speech.tts.TextToSpeech;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import java.util.Locale;

public class MainActivity extends AppCompatActivity implements TextToSpeech.OnInitListener {
    private  static final int TTS_ENGINE_REQUEST =101;
    private TextToSpeech textToSpeech;

    private EditText TextForSpeech;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        TextForSpeech = (EditText)findViewById(R.id.speech_text);
    }

    public void performSpeech(View view) {
        Intent checkIntent = new Intent();
        checkIntent.setAction(TextToSpeech.Engine.ACTION_CHECK_TTS_DATA);
        startActivityForResult(checkIntent,TTS_ENGINE_REQUEST);
    }


    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == TTS_ENGINE_REQUEST && resultCode == TextToSpeech.Engine.CHECK_VOICE_DATA_PASS) {
            textToSpeech = new TextToSpeech(this, this);
        } else {
            Intent installIntent = new Intent();
            installIntent.setAction(TextToSpeech.Engine.ACTION_INSTALL_TTS_DATA);
            startActivity(installIntent);
        }
    }

    @Override
    public void onInit(int status) {
        if (status==TextToSpeech.SUCCESS){
            int languageStatus = textToSpeech.setLanguage(Locale.US);
            if (languageStatus==TextToSpeech.LANG_MISSING_DATA || languageStatus==TextToSpeech.LANG_NOT_SUPPORTED){
                Toast.makeText(this, "Language is not Support..", Toast.LENGTH_SHORT).show();
            }else {
                String data = TextForSpeech.getText().toString();
                int speechStatus = textToSpeech.speak(data,TextToSpeech.QUEUE_FLUSH,null);
                if (speechStatus==TextToSpeech.ERROR){
                    Toast.makeText(this, "Error while Speech..", Toast.LENGTH_SHORT).show();
                }
            }
        }else{
            Toast.makeText(this, "Text to speech engine failed..", Toast.LENGTH_SHORT).show();
        }
    }
}
